name: getx_audio_with_scroll
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  audioplayers: ^6.4.0
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  get: ^4.7.2
  just_audio: ^0.9.46
  just_audio_windows: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/audio/

get_cli:
    sub_folder: false   
